//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VN_number
{
    using System;
    using System.Collections.Generic;
    
    public partial class engineTable
    {
        public int id_engine { get; set; }
        public string code { get; set; }
        public string model { get; set; }
        public string decrypte { get; set; }
    }
}
