//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VN_number
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VinCarDBEntities : DbContext
    {
        public VinCarDBEntities()
            : base("name=VinCarDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bodyTable> bodyTable { get; set; }
        public virtual DbSet<engineTable> engineTable { get; set; }
        public virtual DbSet<firmTable> firmTable { get; set; }
        public virtual DbSet<modelTable> modelTable { get; set; }
        public virtual DbSet<producterTable> producterTable { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<WMITable> WMITable { get; set; }
        public virtual DbSet<suppliersproducterTable> suppliersproducterTable { get; set; }
        public virtual DbSet<supplierTable> supplierTable { get; set; }
    }
}
