//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VN_number
{
    using System;
    using System.Collections.Generic;
    
    public partial class supplierTable
    {
        public int supplier_Id { get; set; }
        public string name { get; set; }
        public string phone { get; set; }
        public int suppliersproducterTable_id { get; set; }
    
        public virtual suppliersproducterTable suppliersproducterTable { get; set; }
    }
}
